export const APARTMENT_HOST_BTN = "APARTMENT_HOST_BTN;";
export const HOUSE_HOST_BTN = "HOUSE_HOST_BTN;";
export const SECONDARYUNIT_HOST_BTN = "SECONDARYUNIT_HOST_BTN;";
export const BEDNBREAKFAST_HOST_BTN = "BEDNBREAKFAST_HOST_BTN;";
export const BOUTIQUEHOTEL_HOST_BTN = "BOUTIQUEHOTEL_HOST_BTN;";

export const RENTALUNIT_HOST_BTN = "RENTALUNIT_HOST_BTN;";
export const LOFT_HOST_BTN = "LOFT_HOST_BTN;";
export const CONDOMINIUM_HOST_BTN = "CONDOMINIUM_HOST_BTN;";

export const ANENTIREPLACE_HOST_BTN = "ANENTIREPLACE_HOST_BTN;";
export const APRIVATEROOM_HOST_BTN = "APRIVATEROOM_HOST_BTN;";
export const ASHAREDROOM_HOST_BTN = "ASHAREDROOM_HOST_BTN;";

export const LOCATION_HOST_INPUT = "LOCATION_HOST_INPUT";

export const GUEST_HOST_BTN = "GUEST_HOST_BTN";
export const BEDS_HOST_BTN = "BEDS_HOST_BTN";
export const BEDSROOMS_HOST_BTN = "BEDSROOMS_HOST_BTN";
export const BATHROOMS_HOST_BTN = "BATHROOMS_HOST_BTN";
