const edata = {
  eHomes: [
    {
      name: "Full House",
      category: "eHomes",
      slug: "huge-home",
      image: "https://i.ibb.co/5rDfLMC/ehomes1.jpg",
      pets: "Pets are not Allowed in this House",
      rating: 4.5,
      description: "A cozy and wonderful home",
      price: 5000,
    },

    {
      name: "3rd Home",
      category: "eHomes",
      image: "https://i.ibb.co/hsk9zPJ/ehomes3.jpg",
      pets: "Pets are not Allowed in this House",
      rating: 4.5,
      description: "A cozy and wonderful home",
      price: 7000,
    },
    {
      name: "2nd Home",
      category: "eHomes",
      image: "https://i.ibb.co/fkdbSxX/ehomes2.jpg",
      pets: "Pets are not Allowed in this House",
      rating: 4.5,
      description: "A cozy and wonderful home",
      price: 10000,
    },
    {
      name: "1st Home Allowing Pets",
      category: "hPets",
      image: "/public/images/p1.jpg",
      rating: 4.8,
      description: "A cozy and wonderful home for you and your pets",
    },
    {
      name: "2nd Home Allowing Pets",
      category: "hPets",
      image: "/public/images/p2.jpg",
      rating: 4.8,
      description: "A cozy and wonderful home for you and your pets",
    },
    {
      name: "3rd Home Allowing Pets",
      category: "hPets",
      image: "/public/images/p3.jpg",
      rating: 4.8,
      description: "A cozy and wonderful home for you and your pets",
    },
    {
      name: "1st Unique Places to Stay",
      category: "uPlace",
      image: "/public/images/uplace1.jpg",
      rating: 4.4,
      description: "A unique and one of a kind place to stay",
    },
    {
      name: "2nd Unique Places to Stay",
      category: "uPlace",
      image: "/public/images/uplace2.jpg",
      rating: 4.4,
      description: "A unique and one of a kind place to stay",
    },
    {
      name: "3rd Unique Places to Stay",
      category: "uPlace",
      image: "/public/images/uplace3.jpg",
      rating: 4.4,
      description: "A unique and one of a kind place to stay",
    },
    {
      name: "1st Home Allowing Pets",
      category: "hPets",
      image: "/public/images/p1.jpg",
      rating: 4.8,
      description: "A cozy and wonderful home for you and your pets",
    },
    {
      name: "2nd Home Allowing Pets",
      category: "hPets",
      image: "/public/images/p2.jpg",
      rating: 4.8,
      description: "A cozy and wonderful home for you and your pets",
    },
    {
      name: "3rd Home Allowing Pets",
      category: "hPets",
      image: "/public/images/p3.jpg",
      rating: 4.8,
      description: "A cozy and wonderful home for you and your pets",
    },
  ],
};
export default edata;
